PACKAGE_NAME="redroid-ashmem"
PACKAGE_VERSION="2.0.0"
CLEAN="make clean"
PRE_BUILD="dkms_pre_build.sh"
MAKE[0]="make all KERNEL_SRC=/lib/modules/$kernelver/build"
POST_BUILD="dkms_post_build.sh"
BUILT_MODULE_NAME[0]="ashmem_linux"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
REMAKE_INITRD="no"

